/** Shared LaTeX for rock-mass symbols. UI renders these via Km / Kblock. */
export const SYM = {
  RMR: String.raw`\mathrm{RMR}`,
  RMR89: String.raw`\mathrm{RMR}_{89}`,
  RMR_formula: String.raw`\mathrm{RMR}=A_1+A_2+A_3+A_4+A_5+A_6`,
  A1: 'A_1',
  A2: 'A_2',
  A3: 'A_3',
  A4: 'A_4',
  A5: 'A_5',
  A6: 'A_6',
  UCS: String.raw`\mathrm{UCS}`,
  RQD: String.raw`\mathrm{RQD}`,
  Is50: String.raw`I_s(50)`,
  pwSigma1: String.raw`p_w/\sigma_1`,
  Q: 'Q',
  Q_formula: String.raw`Q=\frac{\mathrm{RQD}}{J_n}\times\frac{J_r}{J_a}\times\frac{J_w}{\mathrm{SRF}}`,
  Jn: 'J_n',
  Jr: 'J_r',
  Ja: 'J_a',
  Jw: 'J_w',
  SRF: String.raw`\mathrm{SRF}`,
  RQD_over_Jn: String.raw`\mathrm{RQD}/J_n`,
  Jr_over_Ja: String.raw`J_r/J_a`,
  Jw_over_SRF: String.raw`J_w/\mathrm{SRF}`,
  phiR: String.raw`\varphi_r`,
  GSI: String.raw`\mathrm{GSI}`,
  JCond89: String.raw`\mathrm{JCond}_{89}`,
  JCond89_scaled: String.raw`1.5\,\mathrm{JCond}_{89}`,
  RQD_over_2: String.raw`\mathrm{RQD}/2`,
  GSI_quant: String.raw`\mathrm{GSI}=1.5\,\mathrm{JCond}_{89}+\mathrm{RQD}/2`,
  GSI_chart: String.raw`\mathrm{GSI}=\mathrm{Scale}\,A+\mathrm{Scale}\,B`,
  ScaleA: String.raw`\mathrm{Scale}\,A`,
  ScaleB: String.raw`\mathrm{Scale}\,B`,
  ScaleA_quant: String.raw`\mathrm{Scale}\,A=1.5\,\mathrm{JCond}_{89}`,
  ScaleB_quant: String.raw`\mathrm{Scale}\,B=\mathrm{RQD}/2`,
  BQ: String.raw`\mathrm{BQ}`,
  BQ_formula: String.raw`\mathrm{BQ}=100+3R_c+250K_v`,
  BQBracket: String.raw`[\mathrm{BQ}]`,
  Rc: 'R_c',
  Kv: 'K_v',
  RcStar: 'R_c^*',
  KvStar: 'K_v^*',
  K1: 'K_1',
  K2: 'K_2',
  K3: 'K_3',
  K4: 'K_4',
  K5: 'K_5',
  IRMR: String.raw`\mathrm{IRMR}`,
  IRS: String.raw`\mathrm{IRS}`,
  RBS: String.raw`\mathrm{RBS}`,
  JS: String.raw`\mathrm{JS}`,
  JC: String.raw`\mathrm{JC}`,
  MRMR: String.raw`\mathrm{MRMR}`,
} as const

export type SymbolKey = keyof typeof SYM
