import { fireEvent, render, screen } from '@testing-library/react'
import { useState } from 'react'
import { describe, expect, it, vi } from 'vitest'
import QClassificationPage from './components/q/QClassificationPage'
import QModule from './components/q/QModule'
import { createInitialQState, type QFormState } from './methods/q'

function renderPage(initial: QFormState = createInitialQState()) {
  function Harness() {
    const [form, setForm] = useState<Record<string, unknown>>(initial as unknown as Record<string, unknown>)
    return (
      <QClassificationPage
        darkMode={false}
        language="zh"
        caseName="工程"
        pointName="P1"
        pointNote=""
        pointOreType=""
        oreTypeOptions={['花岗岩']}
        pointOrdinal={1}
        pointTotal={1}
        form={form}
        issues={[]}
        result={null}
        onFormChange={setForm}
        onPointNameChange={vi.fn()}
        onPointNoteChange={vi.fn()}
        onPointOreTypeChange={vi.fn()}
        onBackToWorkspace={vi.fn()}
        onBackToPoints={vi.fn()}
        onComplete={vi.fn()}
        onNext={vi.fn()}
      />
    )
  }
  render(<Harness />)
}

describe('Q dedicated page', () => {
  it('opens the Q project workspace without crashing', () => {
    render(<QModule darkMode={false} language="zh" onBackToHome={vi.fn()} />)
    expect(screen.getByRole('heading', { name: /项目工作区/ })).toBeInTheDocument()
  })

  it('keeps introduction, formula and the three factor groups in order', () => {
    renderPage()
    const pointInformation = screen.getByText('点位信息')
    const introduction = screen.getByTestId('q-method-introduction')
    const formula = screen.getByTestId('q-formula')
    const block = screen.getByTestId('q-group-block')
    const shear = screen.getByTestId('q-group-shear')
    const stress = screen.getByTestId('q-group-stress')
    expect(pointInformation.compareDocumentPosition(introduction) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(introduction.compareDocumentPosition(formula) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(formula.compareDocumentPosition(block) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(block.compareDocumentPosition(shear) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(shear.compareDocumentPosition(stress) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(screen.getByTestId('q-formula').textContent).toMatch(/RQD/)
    expect(screen.getByTestId('q-rqd-input')).toBeInTheDocument()
    expect(screen.getByTestId('q-jn-input')).toBeInTheDocument()
    expect(screen.getByTestId('q-jr-input')).toBeInTheDocument()
    expect(screen.getByTestId('q-ja-input')).toBeInTheDocument()
    expect(screen.getByTestId('q-jw-input')).toBeInTheDocument()
    expect(screen.getByTestId('q-srf-input')).toBeInTheDocument()
    expect(screen.getByLabelText('开挖跨度、直径或高度 (m)')).toBeInTheDocument()
    const preview = screen.getByTestId('q-result-preview')
    expect(preview).toHaveTextContent('分值预览')
    expect(preview).toHaveTextContent('已选 0 / 6')
    expect(preview).toHaveTextContent('评价结果')
    expect(preview).toHaveTextContent('输入六项参数后显示正式等级')
  })

  it('labels the reusable rock-mass group field as 岩矿类型', () => {
    renderPage()
    const input = screen.getByLabelText('岩矿类型')
    expect(screen.queryByText('矿岩类型组')).not.toBeInTheDocument()
    expect(input.className).toMatch(/text-center/)
    fireEvent.click(screen.getByRole('button', { name: '打开岩矿类型列表' }))
    expect(screen.getByRole('option', { name: '花岗岩' })).toBeInTheDocument()
  })

  it('keeps point-information inputs centered', () => {
    renderPage()
    const heading = screen.getByRole('heading', { name: '点位信息' })
    expect(heading.className).not.toContain('text-center')
    const section = heading.closest('section')
    expect(section).toBeTruthy()
    const inputs = section!.querySelectorAll('input')
    expect(inputs.length).toBe(4)
    inputs.forEach((input) => {
      expect(input.className).toContain('text-center')
    })
  })

  it('opens the RQD quick calculator from the underlined control', () => {
    renderPage()
    const quick = screen.getByTestId('q-rqd-quick-open')
    expect(quick.parentElement?.className).toContain('justify-end')
    fireEvent.click(quick)
    expect(screen.getByRole('dialog', { name: 'RQD 快速计算' })).toBeInTheDocument()
  })

  it('fills Jn from the Barton table dialog', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jn-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator).toHaveTextContent('节理组数')
    expect(calculator.querySelector('table')?.className).toContain('text-base')
    fireEvent.click(screen.getByTestId('q-factor-row-two_sets'))
    expect(screen.getByTestId('q-jn-result')).toHaveTextContent('= 4')
    expect(screen.getByTestId('q-factor-row-two_sets')).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByTestId('q-factor-row-two_sets').className).toMatch(/font-semibold/)
    expect(screen.getByTestId('q-factor-letter-D').className).toMatch(/bg-blue/)
    expect(screen.queryByTestId('q-ja-clay')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: '确认并回填' }))
    expect(screen.getByTestId('q-jn-input')).toHaveValue(4)
    expect(screen.getByTestId('q-result-preview')).toHaveTextContent('已选 1 / 6')
  })

  it('fills the intersection-modified Jn from the table dialog', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jn-quick-open'))
    fireEvent.click(screen.getByTestId('q-factor-row-two_sets'))
    fireEvent.change(screen.getByTestId('q-jn-site'), { target: { value: 'intersection' } })
    expect(screen.getByTestId('q-jn-result')).toHaveTextContent('= 12')
    fireEvent.click(screen.getByRole('button', { name: '确认并回填' }))
    expect(screen.getByTestId('q-jn-input')).toHaveValue(12)
  })

  it('adds 1 to Jr when the wide-spacing note is selected', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jr-quick-open'))
    fireEvent.click(screen.getByTestId('q-factor-row-rough_undulating'))
    expect(screen.getByTestId('q-jr-result')).toHaveTextContent('= 3')
    expect(screen.getByTestId('q-factor-row-rough_undulating').className).toMatch(/font-semibold/)
    expect(screen.getByTestId('q-factor-row-rough_undulating').querySelector('td')?.className).toMatch(/bg-blue/)
    fireEvent.change(screen.getByTestId('q-jr-note'), { target: { value: 'wide_spacing' } })
    expect(screen.getByTestId('q-jr-result')).toHaveTextContent('= 4')
    fireEvent.click(screen.getByRole('button', { name: '确认并回填' }))
    expect(screen.getByTestId('q-jr-input')).toHaveValue(4)
  })

  it('draws Jr contact-type figures under a, b and c, with roughness profiles only on A–G', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jr-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator).toHaveTextContent('3. 节理粗糙度')
    expect(calculator).toHaveTextContent('（1）节理面完全接触')
    expect(calculator).toHaveTextContent('（2）节理面在剪切错动 10 cm 位移前属于接触')
    expect(calculator).not.toHaveTextContent('（1）节理面完全接触；（2）')
    expect(calculator).toHaveTextContent('（3）剪切过程中节理面不接触')
    expect(calculator).not.toHaveTextContent('（a）节理面完全接触')
    expect(calculator).toHaveTextContent('粗糙或不规则的波状节理')
    expect(calculator).not.toHaveTextContent('已选')
    expect(calculator).not.toHaveTextContent('代入公式的值')
    const note = screen.getByTestId('q-jr-note')
    expect(note).toHaveDisplayValue('无附加修正（按表取值）')
    expect(note).toHaveTextContent('注 1：节理组平均间距 > 3 m，Jr + 1.0')
    expect(note).toHaveTextContent('注 2：带擦痕的平面状节理与最弱方位一致时按 G 档 0.5')
    expect(screen.queryByTestId('q-jr-scale')).toBeNull()
    expect(screen.getByTestId('q-jr-contact-a')).toHaveAttribute('src', './q/jr-wall-contact.png')
    expect(screen.getByTestId('q-jr-contact-b')).toHaveAttribute('src', './q/jr-10cm-shear.png')
    expect(screen.getByTestId('q-jr-contact-c')).toHaveAttribute('src', './q/jr-no-contact.png')
    for (const key of ['a', 'b', 'c'] as const) {
      expect(screen.getByTestId(`q-jr-contact-${key}`).className).toMatch(/h-auto/)
      expect(screen.getByTestId(`q-jr-contact-${key}`).className).not.toMatch(/\bh-1[46]\b/)
    }
    expect(screen.queryByTestId('q-jr-profile-clay_zone_no_contact')).toBeNull()
    expect(screen.queryByTestId('q-jr-profile-crushed_zone_no_contact')).toBeNull()
    const disc = screen.getByTestId('q-jr-profile-discontinuous')
    expect(disc).toHaveTextContent('I')
    expect(disc).toHaveTextContent('粗糙')
    expect(disc).toHaveTextContent('II')
    expect(disc).toHaveTextContent('光滑')
    expect(disc).toHaveTextContent('III')
    expect(disc).toHaveTextContent('擦痕')
    expect(disc.querySelectorAll('img')).toHaveLength(3)
    expect(screen.getByTestId('q-jr-profile-smooth_undulating')).toHaveTextContent('V')
    expect(screen.getByTestId('q-jr-profile-slickensided_planar')).toHaveTextContent('IX')
    expect(screen.getByTestId('q-jr-profile-slickensided_planar').querySelector('img')).toHaveAttribute('src', './q/jr-slickensided_planar.png')
    const discImg = disc.querySelector('img')
    const planarImg = screen.getByTestId('q-jr-profile-slickensided_planar').querySelector('img')
    expect(discImg?.className).toMatch(/\bh-10\b/)
    expect(discImg?.className).toMatch(/\bw-auto\b/)
    expect(discImg?.className).not.toMatch(/\bh-6\b/)
    expect(discImg?.className).not.toMatch(/w-\[18rem\]/)
    expect(planarImg?.className).toBe(discImg?.className)
  })

  it('shows the two Q-system RQD notes in the quick calculator', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-rqd-quick-open'))
    const dialog = screen.getByRole('dialog', { name: 'RQD 快速计算' })
    expect(dialog).toHaveTextContent(/按 5 为间隔/)
    expect(dialog).toHaveTextContent(/名义值 10/)
  })

  it('draws the Jw table with a water-pressure column instead of a copied figure', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jw-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator.querySelector('table')).toBeTruthy()
    expect(calculator.querySelector('img')).toBeNull()
    expect(calculator).toHaveTextContent('5. 节理水折减系数')
    expect(calculator).toHaveTextContent('水压近似值')
    expect(calculator).toHaveTextContent('kg·cm')
    expect(calculator).not.toHaveTextContent('已选')
    expect(calculator).not.toHaveTextContent('注 1：')
    const dryRow = screen.getByTestId('q-factor-row-dry_minor')
    expect(dryRow).toHaveTextContent('<1')
    expect(screen.getByTestId('q-factor-row-large_inflow_unfilled')).toHaveTextContent('2.5～10')
    fireEvent.click(dryRow)
    expect(screen.getByTestId('q-jw-result')).toHaveTextContent('= 1')
    fireEvent.click(screen.getByRole('button', { name: '确认并回填' }))
    expect(screen.getByTestId('q-jw-input')).toHaveValue(1)
  })

  it('draws the Ja table with a residual-friction column', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-ja-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator.querySelector('table')).toBeTruthy()
    expect(calculator.querySelector('img')).toBeNull()
    expect(calculator).toHaveTextContent('4. 节理蚀变系数')
    expect(calculator).not.toHaveTextContent('已选')
    expect(screen.getByTestId('q-factor-row-unaltered_walls')).toHaveTextContent('25～35')
    expect(screen.getByTestId('q-factor-row-silty_sandy_clay_coating')).toHaveTextContent('20～25')
    expect(screen.queryByTestId('q-ja-clay')).toBeNull()
    fireEvent.click(screen.getByTestId('q-factor-letter-K'))
    const clay = screen.getByTestId('q-ja-clay')
    expect(clay).toHaveTextContent('按 G 档黏土状况（强超固结、非软化） · Ja = 6')
    expect(clay).toHaveTextContent('按 J 档黏土状况（膨胀性黏土） · Ja = 8～12')
    fireEvent.change(clay, { target: { value: 'crushed_strong_clay' } })
    expect(screen.getByTestId('q-ja-result')).toHaveTextContent('= 6')
    fireEvent.click(screen.getByRole('button', { name: '确认并回填' }))
    expect(screen.getByTestId('q-ja-input')).toHaveValue(6)
  })

  it('draws the SRF table with book lettering and an inline result', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-srf-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator.querySelector('table')).toBeTruthy()
    expect(calculator.querySelector('img')).toBeNull()
    expect(calculator).toHaveTextContent('6. 应力折减系数')
    expect(calculator).toHaveTextContent('（1）软弱区穿切开挖体，引起岩体松散冒落')
    expect(calculator).toHaveTextContent('（4）膨胀岩化学膨胀')
    expect(calculator).not.toHaveTextContent('已选')
    const loose = screen.getByTestId('q-factor-row-loose_open_joints')
    expect(loose).toHaveTextContent('G')
    expect(screen.getByTestId('q-factor-row-medium_stress')).toHaveTextContent('J')
    expect(screen.getByTestId('q-factor-row-heavy_swelling')).toHaveTextContent('R')
    fireEvent.click(loose)
    expect(screen.getByTestId('q-srf-result')).toHaveTextContent('= 5')
    fireEvent.click(screen.getByRole('button', { name: '确认并回填' }))
    expect(screen.getByTestId('q-srf-input')).toHaveValue(5)
  })

  it('introduces Jn from the NGI definition in a shared auxiliary dialog', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jn-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator.className).toMatch(/(?:^|\s)q-aux-dialog(?:\s|$)/)
    expect(calculator.className).toMatch(/\bmax-w-4xl\b/)
    expect(calculator.className).toMatch(/\bp-6\b/)
    expect(calculator.className).not.toMatch(/max-w-5xl/)
    expect(calculator.className).not.toMatch(/\bw-fit\b/)
    const intro = screen.getByTestId('q-jn-intro')
    expect(intro.className).not.toMatch(/max-w-\[42rem\]/)
    expect(intro).toHaveTextContent('节理组数')
    expect(intro).toHaveTextContent('形成块体')
    expect(intro).toHaveTextContent('同一位置')
    expect(intro).toHaveTextContent('方向数不一定等于节理组数')
  })

  it('introduces Jr and SRF from the NGI handbook', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jr-quick-open'))
    expect(screen.getByTestId('q-jr-intro')).toHaveTextContent('最可能发生剪切')
    expect(screen.getByTestId('q-jr-intro')).toHaveTextContent('手指沿壁面')
    fireEvent.click(screen.getByRole('button', { name: '关闭' }))
    fireEvent.click(screen.getByTestId('q-srf-quick-open'))
    expect(screen.getByTestId('q-factor-calculator').className).toMatch(/(?:^|\s)q-aux-dialog(?:\s|$)/)
    expect(screen.getByTestId('q-srf-intro')).toHaveTextContent('应力与岩石强度')
    expect(screen.getByTestId('q-srf-intro')).toHaveTextContent('只取一个控制性条件')
  })

  it('uses the same width and UI Latin font shell for every Q auxiliary calculator', () => {
    renderPage()
    const expectSharedShell = (dialog: HTMLElement) => {
      expect(dialog.className).toMatch(/(?:^|\s)q-aux-dialog(?:\s|$)/)
      expect(dialog.className).toMatch(/(?:^|\s)thin-scroll(?:\s|$)/)
      expect(dialog.className).toMatch(/\bw-full\b/)
      expect(dialog.className).toMatch(/\bmax-w-4xl\b/)
      expect(dialog.className).toMatch(/\bp-6\b/)
      expect(dialog.className).not.toMatch(/max-w-5xl/)
      expect(dialog.className).not.toMatch(/\bw-fit\b/)
    }

    fireEvent.click(screen.getByTestId('q-rqd-quick-open'))
    const rqd = screen.getByTestId('quick-rqd-calculator')
    expectSharedShell(rqd)
    expect(screen.getByTestId('q-rqd-formula')).toHaveTextContent('长度 ≥ 10 cm 的岩芯累计长度')
    expect(screen.getByTestId('q-rqd-formula')).toHaveTextContent('钻孔长度')
    fireEvent.click(screen.getByRole('button', { name: '关闭' }))

    for (const openId of ['q-jn-quick-open', 'q-jr-quick-open', 'q-ja-quick-open', 'q-jw-quick-open', 'q-srf-quick-open'] as const) {
      fireEvent.click(screen.getByTestId(openId))
      expectSharedShell(screen.getByTestId('q-factor-calculator'))
      fireEvent.click(screen.getByRole('button', { name: '关闭' }))
    }
  })

  it('shows NGI handbook joint-pattern figures in the Jn table', () => {
    renderPage()
    fireEvent.click(screen.getByTestId('q-jn-quick-open'))
    const calculator = screen.getByTestId('q-factor-calculator')
    expect(calculator.querySelector('table')).toBeTruthy()
    expect(calculator).toHaveTextContent('2. 节理组数')
    expect(calculator).toHaveTextContent('块状岩体，无节理或只有少量节理')
    expect(calculator).not.toHaveTextContent('已选')
    expect(calculator).not.toHaveTextContent('代入公式的值')
    expect(screen.getByTestId('q-jn-site')).toHaveDisplayValue('1倍（一般部位）')
    expect(screen.getByLabelText('部位修正').className).toContain('text-sm')
    const figures: Array<[string, string]> = [
      ['one_set', './q/jn-one_set.png'],
      ['two_sets', './q/jn-two_sets.png'],
      ['three_sets', './q/jn-three_sets.png'],
      ['three_sets_random', './q/jn-three_sets_random.png'],
    ]
    for (const [id, src] of figures) {
      expect(screen.getByTestId(`q-jn-sketch-${id}`)).toHaveAttribute('src', src)
    }
    expect(screen.queryByTestId('q-jn-sketch-massive')).toBeNull()
    expect(screen.getByTestId('q-jn-columnar')).toHaveAttribute('src', './q/jn-columnar.png')
    expect(screen.getByTestId('q-jn-columnar').className).toBe(screen.getByTestId('q-jn-sketch-two_sets').className)
    expect(screen.getByTestId('q-jn-sketch-one_set').className).toMatch(/h-28/)
    expect(calculator).toHaveTextContent('柱状节理（三个节理方向）')
    expect(calculator).toHaveTextContent('节理方向数不一定等于节理组数，仍取 Jn = 4')
    expect(screen.getByTestId('q-factor-row-columnar')).toBeInTheDocument()
    fireEvent.click(screen.getByTestId('q-factor-row-columnar'))
    expect(screen.getByTestId('q-jn-result')).toHaveTextContent('= 4')
    expect(screen.getByTestId('q-factor-row-columnar')).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByTestId('q-factor-row-two_sets')).toHaveAttribute('aria-pressed', 'false')
  })

  it('computes Q and the class after the six ratings are entered', () => {
    renderPage()
    fireEvent.change(screen.getByTestId('q-rqd-input'), { target: { value: '80' } })
    fireEvent.change(screen.getByTestId('q-jn-input'), { target: { value: '4' } })
    fireEvent.change(screen.getByTestId('q-jr-input'), { target: { value: '3' } })
    fireEvent.change(screen.getByTestId('q-ja-input'), { target: { value: '1' } })
    fireEvent.change(screen.getByTestId('q-jw-input'), { target: { value: '1' } })
    fireEvent.change(screen.getByTestId('q-srf-input'), { target: { value: '1' } })
    const preview = screen.getByTestId('q-result-preview')
    expect(preview).toHaveTextContent('已选 6 / 6')
    expect(preview).toHaveTextContent('60')
    expect(preview).toHaveTextContent('I 级')
    expect(screen.getByTestId('q-result-analysis')).toHaveTextContent('巴顿岩体质量等级')
    expect(screen.getByTestId('q-result-analysis').querySelector('.text-3xl')).toBeTruthy()
    expect(screen.getByTestId('q-result-substitution').querySelector('.katex')).toBeTruthy()
    expect(screen.getByTestId('q-result-analysis')).not.toHaveTextContent('很好')
    expect(screen.queryByText('九档质量评价与取值说明')).not.toBeInTheDocument()
    expect(screen.getByTestId('q-support-chart')).toBeInTheDocument()
    expect(screen.queryByTestId('q-chart-point')).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('开挖跨度、直径或高度 (m)'), { target: { value: '5' } })
    fireEvent.change(screen.getByLabelText('工程类型 / ESR'), { target: { value: 'major_civil' } })
    expect(screen.getByTestId('q-chart-point')).toBeInTheDocument()
    expect(screen.getByTestId('q-chart-point').querySelectorAll('circle').length).toBeGreaterThanOrEqual(2)
    expect(screen.getByTestId('q-support-chart').compareDocumentPosition(screen.getByTestId('q-support-decision')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(screen.getByTestId('q-support-decision')).toHaveTextContent('无需支护区')
    expect(screen.queryByTestId('q-result-support')).not.toBeInTheDocument()
    expect(screen.getByTestId('q-result-analysis')).not.toHaveTextContent('无需支护区')
    expect(screen.getByTestId('q-result-analysis')).not.toHaveTextContent('支护判定')
    fireEvent.change(screen.getByLabelText('开挖跨度、直径或高度 (m)'), { target: { value: '50' } })
    expect(screen.getByTestId('q-support-decision')).toHaveTextContent('需支护区')
    fireEvent.change(screen.getByLabelText('开挖跨度、直径或高度 (m)'), { target: { value: '' } })
    expect(screen.queryByTestId('q-chart-point')).not.toBeInTheDocument()
    expect(preview).toHaveTextContent('60')
  })

  it('edits temporary-mine ESR beside the type selector and resets it for a fixed ESR', () => {
    renderPage()
    const panel = screen.getByTestId('q-support-panel')
    const header = screen.getByTestId('q-support-header')
    const inputs = screen.getByTestId('q-support-inputs')
    expect(panel).toHaveTextContent('支护需求判定')
    expect(header).toContainElement(screen.getByTestId('q-support-mode'))
    expect(header).toHaveTextContent('无支护极限')
    expect(header).toHaveTextContent('永久支护图')
    expect(header.className).toMatch(/justify-between/)
    expect(panel).not.toHaveTextContent('初判')
    expect(panel).not.toHaveTextContent('照片')
    expect(panel).not.toHaveTextContent('书名')
    expect(screen.getByTestId('q-support-introduction').compareDocumentPosition(screen.getByTestId('q-support-formula')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(screen.getByTestId('q-support-formula').compareDocumentPosition(inputs) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    fireEvent.change(screen.getByLabelText('工程类型 / ESR'), { target: { value: 'temporary_mine' } })
    expect(screen.queryByLabelText('ESR 输入值')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '修改 ESR' }))
    const input = screen.getByLabelText('ESR 输入值')
    expect(header).not.toContainElement(input)
    expect(inputs).toContainElement(input)
    fireEvent.change(input, { target: { value: '4' } })
    fireEvent.blur(input)
    expect(screen.getByRole('button', { name: '修改 ESR' })).toHaveTextContent('4')
    fireEvent.click(screen.getByRole('button', { name: '修改 ESR' }))
    fireEvent.change(screen.getByLabelText('ESR 输入值'), { target: { value: '5' } })
    fireEvent.keyDown(screen.getByLabelText('ESR 输入值'), { key: 'Escape' })
    expect(screen.getByRole('button', { name: '修改 ESR' })).toHaveTextContent('4')
    fireEvent.click(screen.getByRole('button', { name: '修改 ESR' }))
    fireEvent.change(screen.getByLabelText('ESR 输入值'), { target: { value: '3.5' } })
    fireEvent.keyDown(screen.getByLabelText('ESR 输入值'), { key: 'Enter' })
    expect(screen.getByRole('button', { name: '修改 ESR' })).toHaveTextContent('3.5')
    fireEvent.click(screen.getByRole('button', { name: '修改 ESR' }))
    fireEvent.change(screen.getByLabelText('ESR 输入值'), { target: { value: '6' } })
    fireEvent.blur(screen.getByLabelText('ESR 输入值'))
    expect(screen.getByRole('alert')).toHaveTextContent('ESR')
    fireEvent.change(screen.getByLabelText('工程类型 / ESR'), { target: { value: 'major_civil' } })
    expect(screen.queryByRole('button', { name: '修改 ESR' })).not.toBeInTheDocument()
    expect(inputs).toContainElement(screen.getByTestId('q-esr-value'))
    expect(screen.getByTestId('q-esr-value')).toHaveTextContent('1')
    expect(screen.getByTestId('q-esr-value').closest('[data-field="esrValue"]')?.className).toMatch(/w-12/)
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
  })

  it('switches support assessment between the limit chart and the NGI support chart', () => {
    renderPage()
    fireEvent.change(screen.getByTestId('q-rqd-input'), { target: { value: '80' } })
    fireEvent.change(screen.getByTestId('q-jn-input'), { target: { value: '4' } })
    fireEvent.change(screen.getByTestId('q-jr-input'), { target: { value: '3' } })
    fireEvent.change(screen.getByTestId('q-ja-input'), { target: { value: '1' } })
    fireEvent.change(screen.getByTestId('q-jw-input'), { target: { value: '1' } })
    fireEvent.change(screen.getByTestId('q-srf-input'), { target: { value: '1' } })
    fireEvent.change(screen.getByLabelText('开挖跨度、直径或高度 (m)'), { target: { value: '8' } })
    fireEvent.change(screen.getByLabelText('工程类型 / ESR'), { target: { value: 'major_civil' } })
    expect(screen.getByTestId('q-support-header')).toContainElement(screen.getByTestId('q-support-mode'))
    expect(screen.getByRole('button', { name: '无支护极限' })).toHaveClass('bg-blue-600')
    expect(screen.getByTestId('q-support-chart')).toBeInTheDocument()
    expect(screen.queryByTestId('q-ng-support-chart')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '永久支护图' }))
    expect(screen.getByRole('button', { name: '永久支护图' })).toHaveClass('bg-blue-600')
    expect(screen.queryByTestId('q-support-chart')).not.toBeInTheDocument()
    const ngChart = screen.getByTestId('q-ng-support-chart')
    expect(ngChart).toBeInTheDocument()
    expect(ngChart).toHaveTextContent('岩体质量与支护')
    expect(ngChart).toHaveTextContent('异常差')
    expect(ngChart).toHaveTextContent('很好')
    expect(ngChart).toHaveTextContent('当量尺寸 De')
    const letters = ngChart.querySelectorAll('[data-testid="q-ng-quality-letter"]')
    expect([...letters].map((node) => node.textContent)).toEqual(['G', 'F', 'E', 'D', 'C', 'B', 'A'])
    expect([...ngChart.querySelectorAll('[data-testid="q-ng-q-tick"]')].map((node) => node.textContent)).toEqual([
      '0.001', '0.004', '0.01', '0.04', '0.1', '0.4', '1', '4', '10', '40', '100', '400',
    ])
    expect([...ngChart.querySelectorAll('[data-testid="q-ng-de-tick"]')].map((node) => node.textContent)).toEqual([
      '1', '2', '3', '5', '10', '20', '50',
    ])
    expect(ngChart.querySelectorAll('[data-testid="q-ng-category-mark"]')).toHaveLength(9)
    expect(ngChart.querySelector('[data-testid="q-ng-category-mark"] circle')).toBeTruthy()
    const alignedMarks = ['2', '3', '4', '5', '6', '7', '8'].map((id) => ngChart.querySelector(`[data-testid="q-ng-category-mark"][data-category="${id}"] circle`)?.getAttribute('cy'))
    expect(new Set(alignedMarks).size).toBe(1)
    fireEvent.click(screen.getByTestId('q-support-category-row-5'))
    expect(ngChart.querySelector('[data-testid="q-ng-region-highlight"]')).toHaveAttribute('data-category', '5')
    expect(ngChart.querySelector('[data-testid="q-ng-region-highlight"]')).toHaveAttribute('stroke', '#9f1239')
    expect(ngChart.querySelector('[data-testid="q-ng-bolt-tick-20"]')).toHaveTextContent('20')
    expect(screen.getByTestId('q-support-decision')).toHaveTextContent('钢筋喷混凝土肋')
    expect(ngChart.querySelector('[data-testid="q-ng-bolt-axis"]')?.getAttribute('transform')).toMatch(/rotate\(-90\)/)
    const header = ngChart.querySelector('[data-testid="q-ng-header"]')
    const plot = ngChart.querySelector('[data-testid="q-ng-plot"]')
    expect(header).toBeTruthy()
    expect(plot).toBeTruthy()
    expect(Number(plot?.getAttribute('y'))).toBe(Number(header?.getAttribute('y')) + Number(header?.getAttribute('height')))
    expect(ngChart.getAttribute('style')).toMatch(/Segoe UI/)
    expect(ngChart.getAttribute('style')).toMatch(/Noto Sans SC/)
    expect(ngChart.getAttribute('style')).toMatch(/Microsoft YaHei/)
    expect(ngChart.querySelector('[data-testid="q-ng-q-tick"]')?.getAttribute('font-size')).toBe('16')
    const supportRegions = [...ngChart.querySelectorAll('[data-testid="q-ng-support-region"]')]
    expect(supportRegions.map((node) => node.getAttribute('data-category'))).toEqual(['8', '7', '6', '5', '4', '3', '2'])
    expect(new Set(supportRegions.map((node) => node.getAttribute('fill'))).size).toBe(7)
    expect(ngChart.querySelector('linearGradient')).toBeNull()
    expect([...ngChart.querySelectorAll('text')].some((node) => /E\s*=/.test(node.textContent || ''))).toBe(false)
    expect(ngChart.querySelectorAll('[data-testid="q-ng-energy-tooltip"]').length).toBeGreaterThan(0)
    expect([...ngChart.querySelectorAll('[data-testid="q-ng-energy-tooltip"]')].every((node) => /E = (500|700|1000) J/.test(node.getAttribute('aria-label') || ''))).toBe(true)
    expect(ngChart).not.toHaveTextContent('ROCK MASS QUALITY')
    expect(ngChart).not.toHaveTextContent('Exceptionally poor')
    expect(ngChart).not.toHaveTextContent('跨度或高度 / ESR')
    expect(ngChart.parentElement?.className).not.toMatch(/min-w-\[620px\]/)
    expect(screen.getByTestId('q-support-introduction')).toHaveTextContent('永久支护')
    expect(screen.queryByTestId('q-support-legend')).not.toBeInTheDocument()
    expect(screen.getByTestId('q-ng-overlay-bar')).toBeInTheDocument()
    expect(screen.getByRole('checkbox', { name: '喷层厚度数值' })).toBeChecked()
    expect(ngChart.compareDocumentPosition(screen.getByTestId('q-support-decision')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    expect(ngChart).toHaveTextContent('c/c 1.0 m')
    expect(ngChart).not.toHaveTextContent('RRS c/c')
    expect(ngChart).not.toHaveTextContent('有 Sfr 平均锚杆间距')
    expect(ngChart).not.toHaveTextContent('无 Sfr 平均锚杆间距')
    expect(screen.getByTestId('q-support-panel')).not.toHaveTextContent('蓝点')
    expect(screen.getByTestId('q-support-decision')).toHaveTextContent('类别 1')
    expect(screen.getByTestId('q-support-decision')).toHaveTextContent('需专项评价')
    expect(screen.getByTestId('q-support-decision')).not.toHaveTextContent('喷层厚度')
    expect(screen.getByTestId('q-support-metrics').className).toMatch(/\bflex\b/)
    expect(screen.getByTestId('q-support-metrics').children).toHaveLength(3)
    expect(screen.getByTestId('q-support-decision')).not.toHaveTextContent('经验无支护极限')
    expect(screen.getByTestId('q-support-decision')).not.toHaveTextContent('蓝点')
    expect(screen.getByTestId('q-support-decision').className).toMatch(/text-sm/)
    expect(screen.getByTestId('q-support-decision').querySelectorAll('[data-testid="q-support-category-mark"]')).toHaveLength(10)
    expect([...screen.getByTestId('q-support-decision').querySelectorAll('[data-testid="q-support-category-mark"]')].map((node) => node.textContent).slice(1)).toEqual([
      '1', '2', '3', '4', '5', '6', '7', '8', '9',
    ])
    expect(screen.getByTestId('q-result-analysis')).not.toHaveTextContent('类别 1')
    expect(screen.getByTestId('q-result-analysis')).not.toHaveTextContent('支护判定')
    expect(screen.queryByTestId('q-result-support')).not.toBeInTheDocument()
    expect(screen.getByTestId('q-ng-chart-point')).toBeInTheDocument()
    expect(screen.getByTestId('q-ng-chart-point').querySelectorAll('circle')).toHaveLength(2)
    expect(screen.getByTestId('q-ng-chart-point-label')).toHaveTextContent('Q=')
    expect(screen.getByTestId('q-ng-chart-point-label')).toHaveTextContent('De=')

    fireEvent.change(screen.getByTestId('q-rqd-input'), { target: { value: '40' } })
    fireEvent.change(screen.getByTestId('q-jr-input'), { target: { value: '1' } })
    fireEvent.change(screen.getByTestId('q-ja-input'), { target: { value: '10' } })
    expect(screen.getByTestId('q-support-decision')).toHaveTextContent('喷层厚度')
    expect(screen.getByTestId('q-result-analysis')).not.toHaveTextContent('喷层厚度')
    expect(screen.queryByTestId('q-result-support')).not.toBeInTheDocument()
    expect(screen.getByTestId('q-support-decision')).not.toHaveTextContent(/E\s*=?\s*(500|700|1000)/)
  })

  it('flags out-of-range Jn without changing the preview layout', () => {
    renderPage()
    fireEvent.change(screen.getByTestId('q-jn-input'), { target: { value: '61' } })
    expect(screen.getByText('异常值：请输入 0.5～60 范围内的 Jn。')).toBeInTheDocument()
    const preview = screen.getByTestId('q-result-preview')
    expect(preview).toHaveTextContent('已选 0 / 6')
    expect(preview).toHaveTextContent('评价结果')
  })
})
